### ISSUE TITLE
Method storeNote from NoteController should return a JSON response with success status

### ISSUE THREAD

**Issue by jdenisgiguere** [georchestra/notes#1]
NoteController public method storeNote should return a JSON object with the following items:

- "success": {Boolean} : Is the note added?
- "msg" {Text} : Message from server ( _Note stored_ is fine) 

The content-type should be : text/html .

**Comment by Vampouille** [comment]
I can change controller response to a json object but I think mime type should be `application/json`

**Comment by jdenisgiguere** [comment]
You are right, the response will be `application/json`. But, there is a _feature_ ;-) with AJAX response in Ext JS 3.4.0 .

See https://github.com/georchestra/georchestra/pull/1307/files/2e17bfd0b2846da9cadf217c5cb395ac4b9959de#r57205769

**Comment by Vampouille** [comment]
This should be fixed with a5afd80d8cb0cb887e41a4586fbfe4de92a5ce91

**Comment by jdenisgiguere** [comment]
Fixed! Thank you.
